trigger:
  branches:
    include:
      - main

pool: goyal-agent

variables:
  WorkDir: '$(System.DefaultWorkingDirectory)\Environment\dev'

stages:
  - stage: Local_stage

    jobs:
      - job: CI

        steps:
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: '1.14.4'
          - task: TerraformTask@5
            displayName: terraform init       
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(WorkDir)'
              backendServiceArm: 'goyal-app'
              backendAzureRmStorageAccountName: 'storegoyal1121'
              backendAzureRmContainerName: 'cont1'
              backendAzureRmKey: 'terraform.tfstate'

          - task: DownloadSecureFile@1
            displayName: download secure files
            name: tfvarsFile
            inputs:
              secureFile: 'terraform.tfvars'

          - task: TerraformTask@5
            displayName: terraform plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(WorkDir)'
              commandOptions: '-var-file="$(tfvarsFile.secureFilePath)"'
              environmentServiceNameAzureRM: 'goyal-app'

          - task: trivy@2
            inputs:
              version: 'latest'
              type: 'filesystem'
              target: '$(WorkDir)'
              scanners: 'misconfig, secret'
              severities: 'MEDIUM, HIGH, CRITICAL'
              failOnSeverityThreshold: 'CRITICAL'
              reports: 'html'
              publish: true


  - stage: Deploy
    dependsOn: local_stage
    condition: succeeded()
    jobs:
      - job: CD

        steps:
          - task: TerraformInstaller@1
            displayName: terraform install
            inputs:
              terraformVersion: '1.14.4'
          
          - task: TerraformTask@5
            displayName: terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(WorkDir)'
              backendServiceArm: 'goyal-app'
              backendAzureRmStorageAccountName: 'storegoyal1121'
              backendAzureRmContainerName: 'cont1'
              backendAzureRmKey: 'terraform.tfstate'

          - task: DownloadSecureFile@1
            displayName: download secure files
            name: tfvarsFile
            inputs:
              secureFile: 'terraform.tfvars'

          - task: TerraformTask@5
            displayName: terraform plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(WorkDir)'
              commandOptions: '-var-file="$(tfvarsFile.secureFilePath)"'
              environmentServiceNameAzureRM: 'goyal-app'

          - task: trivy@2
            inputs:
              version: 'latest'
              type: 'filesystem'
              target: '$(WorkDir)'
              scanners: 'misconfig, secret'
              severities: 'MEDIUM, HIGH, CRITICAL'
              failOnSeverityThreshold: 'CRITICAL'
              reports: 'html'
              publish: true
          - task: TerraformTask@5
            displayName: terraform apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(WorkDir)'
              commandOptions: '--auto-approve -var-file="$(tfvarsFile.secureFilePath)"'
              environmentServiceNameAzureRM: 'goyal-app'

          - task: TerraformTask@5
            displayName: terraform destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              workingDirectory: '$(WorkDir)'
              commandOptions: '--auto-approve -var-file="$(tfvarsFile.secureFilePath)"'
              environmentServiceNameAzureRM: 'goyal-app'